[workspace]
members = [
    "rxing-detection",
    "rxing-python",
]
resolver = "2" # 推荐使用最新的依赖解析器

[workspace.package]
version = "0.2.0"
authors = ["xiaoniaoyouhuajiang <lie800bili@gamil.com>"]
edition = "2021"
license = "Apache-2.0"

[profile.test]
inherits = "release"

[workspace.dependencies]
usls = {git="https://github.com/jamjamjon/usls"}