[package]
name = "rxing-detection"
# 使用 workspace 中定义的元数据
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "rxing_detection"

[dependencies]
rxing = "0.7.1"
pyo3 = "0.24.0"
rayon = "1.10.0"
anyhow = "1.0.98"
faer = "0.20.1"
sha2 = "0.10.9"
image = { version = "0.25", optional = true } 
imageproc = "0.25.0"
directories = "5.0"
usls = { workspace = true }
reqwest = { version = "0.12" , features = ["blocking"]}
hex = "0.4.3"

[features]
default = ["image"]
